export const ADD_ITEM = "ADD_ITEM"
export const SHOW_FILTER_LIST = "SHOW_FILTER_LIST"
export const UPDATE_ITEM_CONTENT = "UPDATE_ITEM_CONTENT"
export const TOGGLE_ACTIVE = "TOGGLE_ACTIVE"
export const COMPONENT_DID_MOUNT = "COMPONENT_DID_MOUNT"
export const READ = "read"
export const WRITE = "write"
export const MULTIPLICATION = "MULTIPLICATION"